import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.util.Scanner;

public class scanner {
    /**
     * Helper method that generates a version of the original from the current log file
     * @param csvFilePath Path of the log file
     * @return The version of the original generated by following the csv log
     */
	public static String generateFileFromCsv(String csvFilePath)
	{
	    String content = " ";
		try {
		    File csvfile= new File(csvFilePath);
		    if (!csvfile.exists()){
		        csvfile.createNewFile();
            }
			Scanner scanner = new Scanner(csvfile);
			scanner.useDelimiter(",");
			while (scanner.hasNext()) {
			    //Get the necessary information from the csv file
				String type = scanner.next();
                int offset = Integer.parseInt(scanner.next());
                String toChange = scanner.next();
                toChange = toChange.replace('`', ',');
                //If the type is add get the portion of the string starting from index 0 to offset add the new string, and then add the leftover
				if (type.equals("add")) {
                    content = content.substring(0, offset) + toChange + content.substring(offset);
				}
				//If the type is sub then just skip over the portion of the string by manipulating index
				else if (type.equals("sub")) {
					content = content.substring(0, offset) + content.substring(offset + toChange.length());
				}
				//move cursor to next line
				if (scanner.hasNext()) {
					scanner.nextLine();
				}
			}
			scanner.close();

		}
		catch (Exception e) {
		    //Todo: Better Error Handling
			e.printStackTrace();
		}
        return content;
	}
}